package baseAPI.API.Sistema.Enum;

public enum Acao {

    USUARIO_CRIADO,
    USUARIO_EDITADO,
    USUARIO_EXCLUIDO,
    PACOTE_CRIADO,
    PACOTE_EDITADO,
    PACOTE_EXCLUIDO,
    PACOTE_COMENTADO,
    COMENTARIO_EXCLUIDO,
    PACOTE_DOWNLOAD,
    BACKUP_DOWNLOAD;
}
